name: Run Frontend Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Run Frontend Tests with pnpm
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies with pnpm
        run: pnpm install

      - name: Run frontend tests
        run: pnpm test:ci
